'use strict';

const permissionMap = {
  'Super Admin': {
    'contentHomepage': ['home'],
    'branch': ['home', 'view', 'add', 'edit', 'delete'],
    'warehouseInventory': ['home', 'export_excel'],
    'warehouseImport': ['home', 'add', 'edit', 'submit', 'delete'],
    'warehouseExport': ['home', 'add', 'edit', 'submit', 'delete'],
    'warehouseCatalogue': ['home', 'add', 'edit', 'submit', 'delete'],
    'productCategory': ['home', 'add', 'edit', 'delete'],
    'productColor': ['home', 'add', 'edit', 'delete'],
    'productPattern': ['home', 'add', 'edit', 'delete'],
    'productWidth': ['home', 'add', 'edit', 'delete'],
    'productStretch': ['home', 'add', 'edit', 'delete'],
    'productOrigin': ['home', 'add', 'edit', 'delete'],
    'product': ['home', 'add', 'edit', 'delete'],
    'order': [
      'home',
      'view',
      'view_invoice',
      'add',
      'export_excel',
      'create_export',
      'create_invoice',
      'check_success',
      'export_pdf_invoice',
      'cancel'
    ],
    'transactionVNPAY': ['home', 'export_excel'],
    'refund': ['home', 'view', 'view_invoice', 'add', 'export_excel', 'approve', 'export_pdf_invoice'],
    'user': ['home', 'view', 'add', 'edit', 'reset_password', 'delete'],
    'userSchedule': ['home'],
    'userLeave': ['home', 'view', 'add', 'edit', 'delete', 'approve'],
    'voucher': ['home', 'view', 'add', 'edit'],
    'customer': ['home', 'view', 'change_status', 'delete', 'export_excel'],
    'customerDebt': ['home', 'update_debt', 'export_excel'],
    'statisticsRevenue': ['home', 'export_excel'],
    'statisticsSoldvolume': ['home', 'export_excel'],
    'statisticsCustomer': ['home', 'export_excel'],
  },
  'Branch Manager': {
    'warehouseInventory': ['home', 'export_excel'],
    'warehouseImport': ['home', 'add', 'edit', 'submit', 'delete'],
    'warehouseExport': ['home', 'add', 'edit', 'submit', 'delete'],
    'warehouseCatalogue': ['home', 'add', 'edit', 'submit', 'delete'],
    'order': [
      'home',
      'view',
      'view_invoice',
      'add',
      'export_excel',
      'create_export',
      'create_invoice',
      'check_success',
      'export_pdf_invoice',
      'cancel',
    ],
    'refund': ['home', 'view', 'view_invoice', 'add', 'export_excel', 'approve', 'export_pdf_invoice'],
    'user': ['home', 'view', 'add', 'edit', 'reset_password', 'delete'],
    'userSchedule': ['home'],
    'userLeave': ['home', 'view', 'add', 'edit', 'delete', 'approve'],
    'customer': ['home', 'view', 'change_status', 'delete', 'export_excel'],
    'customerDebt': ['home', 'update_debt', 'export_excel'],
    'statisticsRevenue': ['home', 'export_excel'],
    'statisticsSoldvolume': ['home', 'export_excel'],
    'statisticsCustomer': ['home', 'export_excel'],
  },
  'Sales User': {
    'order': [
      'home',
      'view',
      'view_invoice',
      'add',
      'export_excel',
      'create_export',
      'create_invoice',
      'check_success',
      'export_pdf_invoice',
      'cancel',
    ],
    'refund': ['home', 'view', 'view_invoice', 'add', 'export_excel', 'export_pdf_invoice'],
    'customer': ['home', 'view', 'update_debt', 'export_excel'],
    'customerDebt': ['home', 'update_debt', 'export_excel'],
  },
  'Warehouses User': {
    'warehouseInventory': ['home', 'export_excel'],
    'warehouseImport': ['home', 'add', 'edit', 'submit', 'delete'],
    'warehouseExport': ['home', 'add', 'edit', 'submit', 'delete'],
    'warehouseCatalogue': ['home', 'add', 'edit', 'submit', 'delete'],
  },
  'Warehouses User': {
    'warehouseInventory': ['home', 'export_excel'],
    'warehouseImport': ['home', 'add', 'edit', 'submit', 'delete'],
    'warehouseExport': ['home', 'add', 'edit', 'submit', 'delete'],
    'warehouseCatalogue': ['home', 'add', 'edit', 'submit', 'delete'],
  },
  'Accountant': {
    'order': [
      'home',
      'view',
      'view_invoice',
      'export_excel',
      'export_pdf_invoice',
    ],
    'refund': ['home', 'view', 'view_invoice', 'export_excel', 'export_pdf_invoice'],
    'customerDebt': ['export_excel'],
    'statisticsRevenue': ['home', 'export_excel'],
    'statisticsSoldvolume': ['home', 'export_excel'],
    'statisticsCustomer': ['home', 'export_excel'],
  },
}

module.exports = () => ({
  async getPermissionMap(roleName) {
    return permissionMap[roleName];
  },
});
